@server = http://localhost:4004
@auth = Authorization: Basic alice:


### ZSD_T_Customer
# @name ZSD_T_Customer_GET
GET {{server}}/odata/v4/catalog/ZSD_T_Customer
{{auth}}


### ZSD_T_Customer
# @name ZSD_T_Customer_POST
POST {{server}}/odata/v4/catalog/ZSD_T_Customer
Content-Type: application/json
{{auth}}

{
  "ID": 23726927,
  "FirstName": "FirstName-23726927",
  "LastName": "LastName-23726927",
  "SearchTerm": "SearchTerm-23726927",
  "EmiratesId": 81,
  "MobileNumber": "r-23726927",
  "Address": "Address-23726927",
  "Emirates": "Emirates-23726927",
  "City": "City-23726927",
  "Country": "Country-23726927",
  "Reference": "Reference-23726927",
  "VEHICLE": [
    {
      "VehicleGUID": "ZSD_T_VEHICLE-667552",
      "PlateNumber": "ber-667552",
      "PlateSourceCode": 52,
      "PlateSource": "rce-667552",
      "PlateSourceArabic": "bic-667552",
      "PlateColourCode": "ode-667552",
      "PlateColour": "our-667552",
      "PlateColourArabic": "bic-667552",
      "PlateKindCode": 57,
      "PlateKind": "ind-667552",
      "PlateKindArabic": "bic-667552",
      "PlateTypeCode": 27,
      "PlateType": "ype-667552",
      "PlateTypeArabic": "bic-667552",
      "KindCode": 2,
      "Kind": "Kind-667552",
      "KindArabic": "ndArabic-667552",
      "ChassisNumber": "ChassisNumber-667552",
      "EngineNo": "EngineNo-667552",
      "PrimaryVIN": "PrimaryVIN-667552",
      "SecondaryVIN": "SecondaryVIN-667552",
      "CountryCode": "CountryCode-667552",
      "Country": "try-667552",
      "Manufacturer": "rer-667552",
      "ManufacturerArabic": "bic-667552",
      "Model": "del-667552",
      "ModelArabic": "abic-667552",
      "RegistrationYear": 10,
      "TypeCode": 14,
      "Type": "Type-667552",
      "TypeArabic": "TypeArabic-667552",
      "BodyColorCode": 91,
      "BodyColor": "BodyColor-667552",
      "BodyColourArabic": "BodyColourArabic-667552",
      "GearCode": 16,
      "GearType": "ype-667552",
      "GearTypeArabic": "bic-667552",
      "FuelCode": 78,
      "FuelType": "ype-667552",
      "FuelTypeArabic": "bic-667552",
      "SteeringCode": 5,
      "SteeringSide": "ide-667552",
      "SteeringSideArabic": "bic-667552",
      "WeightCode": 72,
      "WeightDisc": "isc-667552",
      "WeightDiscArabic": "bic-667552",
      "RegistrationDate": "2005-08-04",
      "RegistrationExpiryDate": "2004-08-22",
      "ManufacturingYear": "ear-667552",
      "HorsePower": "wer-667552",
      "NumberOfAxel": "xel-667552",
      "NumberOfCylinders": "ers-667552",
      "NumberOfWheels": "els-667552",
      "NumberOfDoors": "ors-667552",
      "NoOfPassenger": "ger-667552",
      "EmptyWeight": "ght-667552",
      "FullWeight": "ght-667552",
      "Mileage": "age-667552",
      "CubicCapCity": "ity-667552",
      "Customer": "mer-667552",
      "CreationDate": "2005-12-06",
      "CreationTime": "2020-12-06",
      "CreatedBy": "CreatedBy-667552",
      "InsuranceName": "InsuranceName-667552",
      "InsuranceExpiry": "2021-05-26",
      "InsuranceKind": "ind-667552",
      "InsuranceKindArabic": "bic-667552",
      "InsurancePoliceNumber": "ePoliceNumber-667552",
      "MortgageDescription": "geDescription-667552",
      "MortgageRef": "MortgageRef-667552",
      "OwnerTCFNumber": "wnerTCFNumber-667552",
      "OwnerTCFArabicName": "OwnerTCFArabicName-667552",
      "OwnerTCFEnglishName": "OwnerTCFEnglishName-667552",
      "CustomCertificateNumber": "ificateNumber-667552",
      "CustomCertificateDate": "2004-10-26",
      "CustomCertificateCenterCode": 37,
      "CustomCertificateCenter": "ificateCenter-667552",
      "RegistrationRemark": "RegistrationRemark-667552",
      "NationalityCode": 83,
      "Nationality": "Nationality-667552",
      "NationalityArabic": "onalityArabic-667552",
      "CustomerReference": "omerReference-667552"
    }
  ]
}


### ZSD_T_Customer
# @name ZSD_T_Customer_PATCH
PATCH {{server}}/odata/v4/catalog/ZSD_T_Customer/23726927
Content-Type: application/json
{{auth}}

{
  "ID": 23726927,
  "FirstName": "FirstName-23726927",
  "LastName": "LastName-23726927",
  "SearchTerm": "SearchTerm-23726927",
  "EmiratesId": 81,
  "MobileNumber": "r-23726927",
  "Address": "Address-23726927",
  "Emirates": "Emirates-23726927",
  "City": "City-23726927",
  "Country": "Country-23726927",
  "Reference": "Reference-23726927",
  "VEHICLE": [
    {
      "VehicleGUID": "ZSD_T_VEHICLE-667552",
      "PlateNumber": "ber-667552",
      "PlateSourceCode": 52,
      "PlateSource": "rce-667552",
      "PlateSourceArabic": "bic-667552",
      "PlateColourCode": "ode-667552",
      "PlateColour": "our-667552",
      "PlateColourArabic": "bic-667552",
      "PlateKindCode": 57,
      "PlateKind": "ind-667552",
      "PlateKindArabic": "bic-667552",
      "PlateTypeCode": 27,
      "PlateType": "ype-667552",
      "PlateTypeArabic": "bic-667552",
      "KindCode": 2,
      "Kind": "Kind-667552",
      "KindArabic": "ndArabic-667552",
      "ChassisNumber": "ChassisNumber-667552",
      "EngineNo": "EngineNo-667552",
      "PrimaryVIN": "PrimaryVIN-667552",
      "SecondaryVIN": "SecondaryVIN-667552",
      "CountryCode": "CountryCode-667552",
      "Country": "try-667552",
      "Manufacturer": "rer-667552",
      "ManufacturerArabic": "bic-667552",
      "Model": "del-667552",
      "ModelArabic": "abic-667552",
      "RegistrationYear": 10,
      "TypeCode": 14,
      "Type": "Type-667552",
      "TypeArabic": "TypeArabic-667552",
      "BodyColorCode": 91,
      "BodyColor": "BodyColor-667552",
      "BodyColourArabic": "BodyColourArabic-667552",
      "GearCode": 16,
      "GearType": "ype-667552",
      "GearTypeArabic": "bic-667552",
      "FuelCode": 78,
      "FuelType": "ype-667552",
      "FuelTypeArabic": "bic-667552",
      "SteeringCode": 5,
      "SteeringSide": "ide-667552",
      "SteeringSideArabic": "bic-667552",
      "WeightCode": 72,
      "WeightDisc": "isc-667552",
      "WeightDiscArabic": "bic-667552",
      "RegistrationDate": "2005-08-04",
      "RegistrationExpiryDate": "2004-08-22",
      "ManufacturingYear": "ear-667552",
      "HorsePower": "wer-667552",
      "NumberOfAxel": "xel-667552",
      "NumberOfCylinders": "ers-667552",
      "NumberOfWheels": "els-667552",
      "NumberOfDoors": "ors-667552",
      "NoOfPassenger": "ger-667552",
      "EmptyWeight": "ght-667552",
      "FullWeight": "ght-667552",
      "Mileage": "age-667552",
      "CubicCapCity": "ity-667552",
      "Customer": "mer-667552",
      "CreationDate": "2005-12-06",
      "CreationTime": "2020-12-06",
      "CreatedBy": "CreatedBy-667552",
      "InsuranceName": "InsuranceName-667552",
      "InsuranceExpiry": "2021-05-26",
      "InsuranceKind": "ind-667552",
      "InsuranceKindArabic": "bic-667552",
      "InsurancePoliceNumber": "ePoliceNumber-667552",
      "MortgageDescription": "geDescription-667552",
      "MortgageRef": "MortgageRef-667552",
      "OwnerTCFNumber": "wnerTCFNumber-667552",
      "OwnerTCFArabicName": "OwnerTCFArabicName-667552",
      "OwnerTCFEnglishName": "OwnerTCFEnglishName-667552",
      "CustomCertificateNumber": "ificateNumber-667552",
      "CustomCertificateDate": "2004-10-26",
      "CustomCertificateCenterCode": 37,
      "CustomCertificateCenter": "ificateCenter-667552",
      "RegistrationRemark": "RegistrationRemark-667552",
      "NationalityCode": 83,
      "Nationality": "Nationality-667552",
      "NationalityArabic": "onalityArabic-667552",
      "CustomerReference": "omerReference-667552"
    }
  ]
}


### ZSD_T_Customer
# @name ZSD_T_Customer_DELETE
DELETE {{server}}/odata/v4/catalog/ZSD_T_Customer/23726927
Content-Type: application/json
{{auth}}


### ZSD_T_VEHICLE
# @name ZSD_T_VEHICLE_GET
GET {{server}}/odata/v4/catalog/ZSD_T_VEHICLE
{{auth}}


### ZSD_T_VEHICLE
# @name ZSD_T_VEHICLE_POST
POST {{server}}/odata/v4/catalog/ZSD_T_VEHICLE
Content-Type: application/json
{{auth}}

{
  "VehicleGUID": "ZSD_T_VEHICLE-667552",
  "PlateNumber": "ber-667552",
  "PlateSourceCode": 52,
  "PlateSource": "rce-667552",
  "PlateSourceArabic": "bic-667552",
  "PlateColourCode": "ode-667552",
  "PlateColour": "our-667552",
  "PlateColourArabic": "bic-667552",
  "PlateKindCode": 57,
  "PlateKind": "ind-667552",
  "PlateKindArabic": "bic-667552",
  "PlateTypeCode": 27,
  "PlateType": "ype-667552",
  "PlateTypeArabic": "bic-667552",
  "KindCode": 2,
  "Kind": "Kind-667552",
  "KindArabic": "ndArabic-667552",
  "ChassisNumber": "ChassisNumber-667552",
  "EngineNo": "EngineNo-667552",
  "PrimaryVIN": "PrimaryVIN-667552",
  "SecondaryVIN": "SecondaryVIN-667552",
  "CountryCode": "CountryCode-667552",
  "Country": "try-667552",
  "Manufacturer": "rer-667552",
  "ManufacturerArabic": "bic-667552",
  "Model": "del-667552",
  "ModelArabic": "abic-667552",
  "RegistrationYear": 10,
  "TypeCode": 14,
  "Type": "Type-667552",
  "TypeArabic": "TypeArabic-667552",
  "BodyColorCode": 91,
  "BodyColor": "BodyColor-667552",
  "BodyColourArabic": "BodyColourArabic-667552",
  "GearCode": 16,
  "GearType": "ype-667552",
  "GearTypeArabic": "bic-667552",
  "FuelCode": 78,
  "FuelType": "ype-667552",
  "FuelTypeArabic": "bic-667552",
  "SteeringCode": 5,
  "SteeringSide": "ide-667552",
  "SteeringSideArabic": "bic-667552",
  "WeightCode": 72,
  "WeightDisc": "isc-667552",
  "WeightDiscArabic": "bic-667552",
  "RegistrationDate": "2005-08-04",
  "RegistrationExpiryDate": "2004-08-22",
  "ManufacturingYear": "ear-667552",
  "HorsePower": "wer-667552",
  "NumberOfAxel": "xel-667552",
  "NumberOfCylinders": "ers-667552",
  "NumberOfWheels": "els-667552",
  "NumberOfDoors": "ors-667552",
  "NoOfPassenger": "ger-667552",
  "EmptyWeight": "ght-667552",
  "FullWeight": "ght-667552",
  "Mileage": "age-667552",
  "CubicCapCity": "ity-667552",
  "Customer": "mer-667552",
  "CreationDate": "2005-12-06",
  "CreationTime": "2020-12-06",
  "CreatedBy": "CreatedBy-667552",
  "InsuranceName": "InsuranceName-667552",
  "InsuranceExpiry": "2021-05-26",
  "InsuranceKind": "ind-667552",
  "InsuranceKindArabic": "bic-667552",
  "InsurancePoliceNumber": "ePoliceNumber-667552",
  "MortgageDescription": "geDescription-667552",
  "MortgageRef": "MortgageRef-667552",
  "OwnerTCFNumber": "wnerTCFNumber-667552",
  "OwnerTCFArabicName": "OwnerTCFArabicName-667552",
  "OwnerTCFEnglishName": "OwnerTCFEnglishName-667552",
  "CustomCertificateNumber": "ificateNumber-667552",
  "CustomCertificateDate": "2004-10-26",
  "CustomCertificateCenterCode": 37,
  "CustomCertificateCenter": "ificateCenter-667552",
  "RegistrationRemark": "RegistrationRemark-667552",
  "NationalityCode": 83,
  "Nationality": "Nationality-667552",
  "NationalityArabic": "onalityArabic-667552",
  "CustomerReference": "omerReference-667552"
}


### ZSD_T_VEHICLE
# @name ZSD_T_VEHICLE_PATCH
PATCH {{server}}/odata/v4/catalog/ZSD_T_VEHICLE/ZSD_T_VEHICLE-667552
Content-Type: application/json
{{auth}}

{
  "VehicleGUID": "ZSD_T_VEHICLE-667552",
  "PlateNumber": "ber-667552",
  "PlateSourceCode": 52,
  "PlateSource": "rce-667552",
  "PlateSourceArabic": "bic-667552",
  "PlateColourCode": "ode-667552",
  "PlateColour": "our-667552",
  "PlateColourArabic": "bic-667552",
  "PlateKindCode": 57,
  "PlateKind": "ind-667552",
  "PlateKindArabic": "bic-667552",
  "PlateTypeCode": 27,
  "PlateType": "ype-667552",
  "PlateTypeArabic": "bic-667552",
  "KindCode": 2,
  "Kind": "Kind-667552",
  "KindArabic": "ndArabic-667552",
  "ChassisNumber": "ChassisNumber-667552",
  "EngineNo": "EngineNo-667552",
  "PrimaryVIN": "PrimaryVIN-667552",
  "SecondaryVIN": "SecondaryVIN-667552",
  "CountryCode": "CountryCode-667552",
  "Country": "try-667552",
  "Manufacturer": "rer-667552",
  "ManufacturerArabic": "bic-667552",
  "Model": "del-667552",
  "ModelArabic": "abic-667552",
  "RegistrationYear": 10,
  "TypeCode": 14,
  "Type": "Type-667552",
  "TypeArabic": "TypeArabic-667552",
  "BodyColorCode": 91,
  "BodyColor": "BodyColor-667552",
  "BodyColourArabic": "BodyColourArabic-667552",
  "GearCode": 16,
  "GearType": "ype-667552",
  "GearTypeArabic": "bic-667552",
  "FuelCode": 78,
  "FuelType": "ype-667552",
  "FuelTypeArabic": "bic-667552",
  "SteeringCode": 5,
  "SteeringSide": "ide-667552",
  "SteeringSideArabic": "bic-667552",
  "WeightCode": 72,
  "WeightDisc": "isc-667552",
  "WeightDiscArabic": "bic-667552",
  "RegistrationDate": "2005-08-04",
  "RegistrationExpiryDate": "2004-08-22",
  "ManufacturingYear": "ear-667552",
  "HorsePower": "wer-667552",
  "NumberOfAxel": "xel-667552",
  "NumberOfCylinders": "ers-667552",
  "NumberOfWheels": "els-667552",
  "NumberOfDoors": "ors-667552",
  "NoOfPassenger": "ger-667552",
  "EmptyWeight": "ght-667552",
  "FullWeight": "ght-667552",
  "Mileage": "age-667552",
  "CubicCapCity": "ity-667552",
  "Customer": "mer-667552",
  "CreationDate": "2005-12-06",
  "CreationTime": "2020-12-06",
  "CreatedBy": "CreatedBy-667552",
  "InsuranceName": "InsuranceName-667552",
  "InsuranceExpiry": "2021-05-26",
  "InsuranceKind": "ind-667552",
  "InsuranceKindArabic": "bic-667552",
  "InsurancePoliceNumber": "ePoliceNumber-667552",
  "MortgageDescription": "geDescription-667552",
  "MortgageRef": "MortgageRef-667552",
  "OwnerTCFNumber": "wnerTCFNumber-667552",
  "OwnerTCFArabicName": "OwnerTCFArabicName-667552",
  "OwnerTCFEnglishName": "OwnerTCFEnglishName-667552",
  "CustomCertificateNumber": "ificateNumber-667552",
  "CustomCertificateDate": "2004-10-26",
  "CustomCertificateCenterCode": 37,
  "CustomCertificateCenter": "ificateCenter-667552",
  "RegistrationRemark": "RegistrationRemark-667552",
  "NationalityCode": 83,
  "Nationality": "Nationality-667552",
  "NationalityArabic": "onalityArabic-667552",
  "CustomerReference": "omerReference-667552"
}


### ZSD_T_VEHICLE
# @name ZSD_T_VEHICLE_DELETE
DELETE {{server}}/odata/v4/catalog/ZSD_T_VEHICLE/ZSD_T_VEHICLE-667552
Content-Type: application/json
{{auth}}
