@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Zsd_T_Test_Masters
# @name Zsd_T_Test_Masters_GET
GET {{server}}/odata/v4/catalog/Zsd_T_Test_Masters
{{auth}}


### Zsd_T_Test_Masters
# @name Zsd_T_Test_Masters_POST
POST {{server}}/odata/v4/catalog/Zsd_T_Test_Masters
Content-Type: application/json
{{auth}}

  {
    "zTestTypeText": "Steering system and suspension stability",
    "zTestTypeTextAE": "نظام التوجيه واستقرار نظام التعليق"
  }

### Zsd_T_Test_Masters
# @name Zsd_T_Test_Masters_PATCH
PATCH {{server}}/odata/v4/catalog/Zsd_T_Test_Masters/11336783-8768-4f94-8a9f-d6b9f4c3b46b
Content-Type: application/json
{{auth}}

{
  "guid": "11336783-8768-4f94-8a9f-d6b9f4c3b46b",
  "zFiledMapping": "6783",
  "zTest": 62,
  "zTestText": "zTestText-11336783",
  "zTestType": 78,
  "zTestSubType": 81,
  "zTestTypeText": "zTestTypeText-11336783",
  "zTestTypeTextAE": "zTestTypeTextAE-11336783",
  "zSubTypeText": "zSubTypeText-11336783",
  "zSubTypeTextAE": "zSubTypeTextAE-11336783",
  "zExaminationMethod": "ationMethod-11336783",
  "zAllow1": "zAllow1-11336783",
  "zAllow2": "zAllow2-11336783",
  "zAllow3": "zAllow3-11336783",
  "zAllow4": "zAllow4-11336783",
  "zValue1": "zValue1-11336783",
  "zValue2": "zValue2-11336783",
  "zValue3": "zValue3-11336783",
  "zValue4": "zValue4-11336783",
  "createdAt": "2009-04-02T00:00:00.000Z",
  "createdBy": "createdBy.6qzin@example.org",
  "modifiedAt": "2002-10-20T00:00:00.000Z",
  "modifiedBy": "modifiedBy.6qzin@example.net"
}


### Zsd_T_Test_Masters
# @name Zsd_T_Test_Masters_DELETE
DELETE {{server}}/odata/v4/catalog/Zsd_T_Test_Masters/11336783-8768-4f94-8a9f-d6b9f4c3b46b
Content-Type: application/json
{{auth}}


### Zsd_T_Test_Results
# @name Zsd_T_Test_Results_GET
GET {{server}}/odata/v4/catalog/Zsd_T_Test_Results
{{auth}}


### Zsd_T_Test_Results
# @name Zsd_T_Test_Results_POST
POST {{server}}/odata/v4/catalog/Zsd_T_Test_Results
Content-Type: application/json
{{auth}}

{
  "guid": "24315307-0e80-4ad6-98e9-eadb52789cfc",
  "VBELN": "N-24315307",
  "POSNR": 96,
  "zTest": 18,
  "zF1": false,
  "zF2": false,
  "zF3": false,
  "zF4": false,
  "zF5": false,
  "zF6": false,
  "zF7": false,
  "zF8": false,
  "zF9": false,
  "zF10": false,
  "zF11": false,
  "zF12": false,
  "zF13": false,
  "zF14": false,
  "zF15": false,
  "zF16": false,
  "zF17": false,
  "zF18": false,
  "zF19": false,
  "zF20": false,
  "createdAt": "2011-08-29T00:00:00.000Z",
  "createdBy": "createdBy.eh5t7@example.com",
  "modifiedAt": "2016-05-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy.eh5t7@example.net"
}


### Zsd_T_Test_Results
# @name Zsd_T_Test_Results_PATCH
PATCH {{server}}/odata/v4/catalog/Zsd_T_Test_Results/24315307-0e80-4ad6-98e9-eadb52789cfc
Content-Type: application/json
{{auth}}

{
  "guid": "24315307-0e80-4ad6-98e9-eadb52789cfc",
  "VBELN": "N-24315307",
  "POSNR": 96,
  "zTest": 18,
  "zF1": false,
  "zF2": false,
  "zF3": false,
  "zF4": false,
  "zF5": false,
  "zF6": false,
  "zF7": false,
  "zF8": false,
  "zF9": false,
  "zF10": false,
  "zF11": false,
  "zF12": false,
  "zF13": false,
  "zF14": false,
  "zF15": false,
  "zF16": false,
  "zF17": false,
  "zF18": false,
  "zF19": false,
  "zF20": false,
  "createdAt": "2011-08-29T00:00:00.000Z",
  "createdBy": "createdBy.eh5t7@example.com",
  "modifiedAt": "2016-05-06T00:00:00.000Z",
  "modifiedBy": "modifiedBy.eh5t7@example.net"
}


### Zsd_T_Test_Results
# @name Zsd_T_Test_Results_DELETE
DELETE {{server}}/odata/v4/catalog/Zsd_T_Test_Results/24315307-0e80-4ad6-98e9-eadb52789cfc
Content-Type: application/json
{{auth}}
