@server = http://localhost:4004
@auth = Authorization: Basic alice:


### CustomerMasters
# @name CustomerMasters_GET
GET {{server}}/odata/v4/catalog/CustomerMasters
{{auth}}


### CustomerMasters
# @name CustomerMasters_POST
POST {{server}}/odata/v4/catalog/CustomerMasters
Content-Type: application/json
{{auth}}

{
    "customerNo": null,
    "emiratesId": "t",
    "firstName": "T",
    "lastName": null,
    "mobileNo": "6666666666",
    "region": null,
    "BPGrouping": null,
    "extReference": null,
    "emailAddress": "dukumar@gmail.com",
    "vehicleMasters": [
        {
            "plateNumber": "5",
            "plateSourceCode": "6",
            "plateSource": null,
            "plateSourceArabic": null,
            "plateColorCode": null,
            "plateColor": null,
            "plateColorArabic": null,
            "plateKindCode": null,
            "plateKind": null,
            "plateKindArabic": null,
            "plateTypeCode": null,
            "plateType": null,
            "plateTypeArabic": null,
            "kindCode": null,
            "kind": null,
            "kindArabic": null,
            "chasisNumber": "         12345678908765432",
            "engineNumber": "325678997",
            "primaryVin": null,
            "secondaryVin": null,
            "countryCode": null,
            "country": null,
            "manfacturerCode": null,
            "manfacturer": "t",
            "manfacturerArabic": null,
            "modelCode": null,
            "model": "t",
            "modelArabic": null,
            "registrationYear": null,
            "typeCode": null,
            "type": null,
            "typeArabic": null,
            "bodyColorCode": null,
            "bodyColor": null,
            "bodyColorArabic": null,
            "gearCode": null,
            "gearType": null,
            "gearTypeArabic": null,
            "fuelCode": null,
            "fuelType": null,
            "fuelTypeArabic": null,
            "steeringCode": null,
            "steeringSide": null,
            "steeringSideArabic": null,
            "weightCode": null,
            "weightDisc": null,
            "weightDiscArabic": null,
            "registrationDate": null,
            "registrationExpiryDate": null,
            "manufacturingYear": null,
            "horsePower": null,
            "numberOfAxel": null,
            "numberOfWheels": null,
            "numberOfCylinders": null,
            "numberOfDoors": null,
            "numberOfPassengers": null,
            "emptyWeight": null,
            "fullWeight": null,
            "mileage": null,
            "cubicCapacity": null,
            "customer": null,
            "insuranceName": null,
            "insuranceExpiry": null,
            "insuranceKind": null,
            "insuranceKindArabic": null,
            "insurancePolicyNumber": null,
            "mortgageDescription": null,
            "mortgageReference": null,
            "ownerTcfNumber": null,
            "ownerTcfEnglishName": null,
            "ownerTcfArabicName": null,
            "customCertificateNumber": null,
            "customCertificateDate": null,
            "customCertificateCenterCode": null,
            "customCertificateCenter": null,
            "registrationRemarks": null,
            "nationalityCode": null,
            "nationality": null,
            "nationalityArabic": null
        }
    ]
}


### CustomerMasters
# @name CustomerMasters_PATCH
PATCH {{server}}/odata/v4/catalog/CustomerMasters/43560037-e607-45a9-8bde-f36317dc10fc
Content-Type: application/json
{{auth}}

{
  "customersUUID": "43560037-e607-45a9-8bde-f36317dc10fc",
  "customerNo": 17,
  "emiratesId": "emiratesId-435600",
  "firstName": "firstName-435600",
  "lastName": "lastName-435600",
  "mobileNo": "mobileNo-435600",
  "region": "region-435600",
  "BPGrouping": "BPGrouping-435600",
  "extReference": "extReference-435600",
  "emailAddress": "emailAddress-435600",
  "vehicleMasters": [
    {
      "vehicleMastersUUID": "16591862-333e-47fc-a2aa-80e763f4769b",
      "plateNumber": "plateNumber-16591862",
      "plateSourceCode": "plateSourceCode-16591862",
      "plateSource": "plateSource-16591862",
      "plateSourceArabic": "plateSourceArabic-16591862",
      "plateColorCode": "plateColorCode-16591862",
      "plateColor": "plateColor-16591862",
      "plateColorArabic": "plateColorArabic-16591862",
      "plateKindCode": "plateKindCode-16591862",
      "plateKind": "plateKind-16591862",
      "plateKindArabic": "plateKindArabic-16591862",
      "plateTypeCode": "plateTypeCode-16591862",
      "plateType": "plateType-16591862",
      "plateTypeArabic": "plateTypeArabic-16591862",
      "kindCode": "kindCode-16591862",
      "kind": "kind-16591862",
      "kindArabic": "kindArabic-16591862",
      "chasisNumber": "chasisNumber-16591862",
      "engineNumber": "engineNumber-16591862",
      "primaryVin": "primaryVin-16591862",
      "secondaryVin": "secondaryVin-16591862",
      "countryCode": "countryCode-16591862",
      "country": "country-16591862",
      "manfacturerCode": "manfacturerCode-16591862",
      "manfacturer": "manfacturer-16591862",
      "manfacturerArabic": "manfacturerArabic-16591862",
      "modelCode": "modelCode-16591862",
      "model": "model-16591862",
      "modelArabic": "modelArabic-16591862",
      "registrationYear": "registrationYear-16591862",
      "typeCode": "typeCode-16591862",
      "type": "type-16591862",
      "typeArabic": "typeArabic-16591862",
      "bodyColorCode": "bodyColorCode-16591862",
      "bodyColor": "bodyColor-16591862",
      "bodyColorArabic": "bodyColorArabic-16591862",
      "gearCode": "gearCode-16591862",
      "gearType": "gearType-16591862",
      "gearTypeArabic": "gearTypeArabic-16591862",
      "fuelCode": "fuelCode-16591862",
      "fuelType": "fuelType-16591862",
      "fuelTypeArabic": "fuelTypeArabic-16591862",
      "steeringCode": "steeringCode-16591862",
      "steeringSide": "steeringSide-16591862",
      "steeringSideArabic": "steeringSideArabic-16591862",
      "weightCode": "weightCode-16591862",
      "weightDisc": "weightDisc-16591862",
      "weightDiscArabic": "weightDiscArabic-16591862",
      "registrationDate": "2020-11-04T00:00:00.000Z",
      "registrationExpiryDate": "2004-06-10T00:00:00.000Z",
      "manufacturingYear": "manufacturingYear-16591862",
      "horsePower": "horsePower-16591862",
      "numberOfAxel": "numberOfAxel-16591862",
      "numberOfWheels": "numberOfWheels-16591862",
      "numberOfCylinders": "numberOfCylinders-16591862",
      "numberOfDoors": "numberOfDoors-16591862",
      "numberOfPassengers": "numberOfPassengers-16591862",
      "emptyWeight": "emptyWeight-16591862",
      "fullWeight": "fullWeight-16591862",
      "mileage": "mileage-16591862",
      "cubicCapacity": "cubicCapacity-16591862",
      "customer": "customer-16591862",
      "insuranceName": "insuranceName-16591862",
      "insuranceExpiry": "insuranceExpiry-16591862",
      "insuranceKind": "insuranceKind-16591862",
      "insuranceKindArabic": "insuranceKindArabic-16591862",
      "insurancePolicyNumber": "insurancePolicyNumber-16591862",
      "mortgageDescription": "mortgageDescription-16591862",
      "mortgageReference": "mortgageReference-16591862",
      "ownerTcfNumber": "ownerTcfNumber-16591862",
      "ownerTcfEnglishName": "ownerTcfEnglishName-16591862",
      "ownerTcfArabicName": "ownerTcfArabicName-16591862",
      "customCertificateNumber": "customCertificateNumber-16591862",
      "customCertificateDate": "2017-07-02T00:00:00.000Z",
      "customCertificateCenterCode": "customCertificateCenterCode-16591862",
      "customCertificateCenter": "customCertificateCenter-16591862",
      "registrationRemarks": "registrationRemarks-16591862",
      "nationalityCode": "nationalityCode-16591862",
      "nationality": "nationality-16591862",
      "nationalityArabic": "nationalityArabic-16591862",
      "createdAt": "2004-03-22T00:00:00.000Z",
      "createdBy": "createdBy.9vmd2@example.net",
      "modifiedAt": "2019-09-28T00:00:00.000Z",
      "modifiedBy": "modifiedBy.9vmd2@example.com"
    },
    {
      "vehicleMastersUUID": "16591863-d2cb-41cf-8c56-d4dd999d7c15",
      "plateNumber": "plateNumber-16591863",
      "plateSourceCode": "plateSourceCode-16591863",
      "plateSource": "plateSource-16591863",
      "plateSourceArabic": "plateSourceArabic-16591863",
      "plateColorCode": "plateColorCode-16591863",
      "plateColor": "plateColor-16591863",
      "plateColorArabic": "plateColorArabic-16591863",
      "plateKindCode": "plateKindCode-16591863",
      "plateKind": "plateKind-16591863",
      "plateKindArabic": "plateKindArabic-16591863",
      "plateTypeCode": "plateTypeCode-16591863",
      "plateType": "plateType-16591863",
      "plateTypeArabic": "plateTypeArabic-16591863",
      "kindCode": "kindCode-16591863",
      "kind": "kind-16591863",
      "kindArabic": "kindArabic-16591863",
      "chasisNumber": "chasisNumber-16591863",
      "engineNumber": "engineNumber-16591863",
      "primaryVin": "primaryVin-16591863",
      "secondaryVin": "secondaryVin-16591863",
      "countryCode": "countryCode-16591863",
      "country": "country-16591863",
      "manfacturerCode": "manfacturerCode-16591863",
      "manfacturer": "manfacturer-16591863",
      "manfacturerArabic": "manfacturerArabic-16591863",
      "modelCode": "modelCode-16591863",
      "model": "model-16591863",
      "modelArabic": "modelArabic-16591863",
      "registrationYear": "registrationYear-16591863",
      "typeCode": "typeCode-16591863",
      "type": "type-16591863",
      "typeArabic": "typeArabic-16591863",
      "bodyColorCode": "bodyColorCode-16591863",
      "bodyColor": "bodyColor-16591863",
      "bodyColorArabic": "bodyColorArabic-16591863",
      "gearCode": "gearCode-16591863",
      "gearType": "gearType-16591863",
      "gearTypeArabic": "gearTypeArabic-16591863",
      "fuelCode": "fuelCode-16591863",
      "fuelType": "fuelType-16591863",
      "fuelTypeArabic": "fuelTypeArabic-16591863",
      "steeringCode": "steeringCode-16591863",
      "steeringSide": "steeringSide-16591863",
      "steeringSideArabic": "steeringSideArabic-16591863",
      "weightCode": "weightCode-16591863",
      "weightDisc": "weightDisc-16591863",
      "weightDiscArabic": "weightDiscArabic-16591863",
      "registrationDate": "2020-04-23T00:00:00.000Z",
      "registrationExpiryDate": "2003-09-02T00:00:00.000Z",
      "manufacturingYear": "manufacturingYear-16591863",
      "horsePower": "horsePower-16591863",
      "numberOfAxel": "numberOfAxel-16591863",
      "numberOfWheels": "numberOfWheels-16591863",
      "numberOfCylinders": "numberOfCylinders-16591863",
      "numberOfDoors": "numberOfDoors-16591863",
      "numberOfPassengers": "numberOfPassengers-16591863",
      "emptyWeight": "emptyWeight-16591863",
      "fullWeight": "fullWeight-16591863",
      "mileage": "mileage-16591863",
      "cubicCapacity": "cubicCapacity-16591863",
      "customer": "customer-16591863",
      "insuranceName": "insuranceName-16591863",
      "insuranceExpiry": "insuranceExpiry-16591863",
      "insuranceKind": "insuranceKind-16591863",
      "insuranceKindArabic": "insuranceKindArabic-16591863",
      "insurancePolicyNumber": "insurancePolicyNumber-16591863",
      "mortgageDescription": "mortgageDescription-16591863",
      "mortgageReference": "mortgageReference-16591863",
      "ownerTcfNumber": "ownerTcfNumber-16591863",
      "ownerTcfEnglishName": "ownerTcfEnglishName-16591863",
      "ownerTcfArabicName": "ownerTcfArabicName-16591863",
      "customCertificateNumber": "customCertificateNumber-16591863",
      "customCertificateDate": "2013-02-04T00:00:00.000Z",
      "customCertificateCenterCode": "customCertificateCenterCode-16591863",
      "customCertificateCenter": "customCertificateCenter-16591863",
      "registrationRemarks": "registrationRemarks-16591863",
      "nationalityCode": "nationalityCode-16591863",
      "nationality": "nationality-16591863",
      "nationalityArabic": "nationalityArabic-16591863",
      "createdAt": "2008-11-03T00:00:00.000Z",
      "createdBy": "createdBy.9vmd3@example.com",
      "modifiedAt": "2005-09-17T00:00:00.000Z",
      "modifiedBy": "modifiedBy.9vmd3@example.org"
    }
  ],
  "createdAt": "2000-09-21T00:00:00.000Z",
  "createdBy": "createdBy.9c40@example.org",
  "modifiedAt": "2004-03-21T00:00:00.000Z",
  "modifiedBy": "modifiedBy.9c40@example.net"
}


### CustomerMasters
# @name CustomerMasters_DELETE
DELETE {{server}}/odata/v4/catalog/CustomerMasters/43560037-e607-45a9-8bde-f36317dc10fc
Content-Type: application/json
{{auth}}


### VehicleMasters
# @name VehicleMasters_GET
GET {{server}}/odata/v4/catalog/VehicleMasters
{{auth}}


### VehicleMasters
# @name VehicleMasters_POST
POST {{server}}/odata/v4/catalog/VehicleMasters
Content-Type: application/json
{{auth}}

{
  "vehicleMastersUUID": "16591862-333e-47fc-a2aa-80e763f4769b",
  "plateNumber": "plateNumber-16591862",
  "plateSourceCode": "plateSourceCode-16591862",
  "plateSource": "plateSource-16591862",
  "plateSourceArabic": "plateSourceArabic-16591862",
  "plateColorCode": "plateColorCode-16591862",
  "plateColor": "plateColor-16591862",
  "plateColorArabic": "plateColorArabic-16591862",
  "plateKindCode": "plateKindCode-16591862",
  "plateKind": "plateKind-16591862",
  "plateKindArabic": "plateKindArabic-16591862",
  "plateTypeCode": "plateTypeCode-16591862",
  "plateType": "plateType-16591862",
  "plateTypeArabic": "plateTypeArabic-16591862",
  "kindCode": "kindCode-16591862",
  "kind": "kind-16591862",
  "kindArabic": "kindArabic-16591862",
  "chasisNumber": "chasisNumber-16591862",
  "engineNumber": "engineNumber-16591862",
  "primaryVin": "primaryVin-16591862",
  "secondaryVin": "secondaryVin-16591862",
  "countryCode": "countryCode-16591862",
  "country": "country-16591862",
  "manfacturerCode": "manfacturerCode-16591862",
  "manfacturer": "manfacturer-16591862",
  "manfacturerArabic": "manfacturerArabic-16591862",
  "modelCode": "modelCode-16591862",
  "model": "model-16591862",
  "modelArabic": "modelArabic-16591862",
  "registrationYear": "registrationYear-16591862",
  "typeCode": "typeCode-16591862",
  "type": "type-16591862",
  "typeArabic": "typeArabic-16591862",
  "bodyColorCode": "bodyColorCode-16591862",
  "bodyColor": "bodyColor-16591862",
  "bodyColorArabic": "bodyColorArabic-16591862",
  "gearCode": "gearCode-16591862",
  "gearType": "gearType-16591862",
  "gearTypeArabic": "gearTypeArabic-16591862",
  "fuelCode": "fuelCode-16591862",
  "fuelType": "fuelType-16591862",
  "fuelTypeArabic": "fuelTypeArabic-16591862",
  "steeringCode": "steeringCode-16591862",
  "steeringSide": "steeringSide-16591862",
  "steeringSideArabic": "steeringSideArabic-16591862",
  "weightCode": "weightCode-16591862",
  "weightDisc": "weightDisc-16591862",
  "weightDiscArabic": "weightDiscArabic-16591862",
  "registrationDate": "2020-11-04T00:00:00.000Z",
  "registrationExpiryDate": "2004-06-10T00:00:00.000Z",
  "manufacturingYear": "manufacturingYear-16591862",
  "horsePower": "horsePower-16591862",
  "numberOfAxel": "numberOfAxel-16591862",
  "numberOfWheels": "numberOfWheels-16591862",
  "numberOfCylinders": "numberOfCylinders-16591862",
  "numberOfDoors": "numberOfDoors-16591862",
  "numberOfPassengers": "numberOfPassengers-16591862",
  "emptyWeight": "emptyWeight-16591862",
  "fullWeight": "fullWeight-16591862",
  "mileage": "mileage-16591862",
  "cubicCapacity": "cubicCapacity-16591862",
  "customer": "customer-16591862",
  "insuranceName": "insuranceName-16591862",
  "insuranceExpiry": "insuranceExpiry-16591862",
  "insuranceKind": "insuranceKind-16591862",
  "insuranceKindArabic": "insuranceKindArabic-16591862",
  "insurancePolicyNumber": "insurancePolicyNumber-16591862",
  "mortgageDescription": "mortgageDescription-16591862",
  "mortgageReference": "mortgageReference-16591862",
  "ownerTcfNumber": "ownerTcfNumber-16591862",
  "ownerTcfEnglishName": "ownerTcfEnglishName-16591862",
  "ownerTcfArabicName": "ownerTcfArabicName-16591862",
  "customCertificateNumber": "customCertificateNumber-16591862",
  "customCertificateDate": "2017-07-02T00:00:00.000Z",
  "customCertificateCenterCode": "customCertificateCenterCode-16591862",
  "customCertificateCenter": "customCertificateCenter-16591862",
  "registrationRemarks": "registrationRemarks-16591862",
  "nationalityCode": "nationalityCode-16591862",
  "nationality": "nationality-16591862",
  "nationalityArabic": "nationalityArabic-16591862",
  "createdAt": "2004-03-22T00:00:00.000Z",
  "createdBy": "createdBy.9vmd2@example.net",
  "modifiedAt": "2019-09-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.9vmd2@example.com"
}


### VehicleMasters
# @name VehicleMasters_PATCH
PATCH {{server}}/odata/v4/catalog/VehicleMasters/16591862-333e-47fc-a2aa-80e763f4769b
Content-Type: application/json
{{auth}}

{
  "vehicleMastersUUID": "16591862-333e-47fc-a2aa-80e763f4769b",
  "plateNumber": "plateNumber-16591862",
  "plateSourceCode": "plateSourceCode-16591862",
  "plateSource": "plateSource-16591862",
  "plateSourceArabic": "plateSourceArabic-16591862",
  "plateColorCode": "plateColorCode-16591862",
  "plateColor": "plateColor-16591862",
  "plateColorArabic": "plateColorArabic-16591862",
  "plateKindCode": "plateKindCode-16591862",
  "plateKind": "plateKind-16591862",
  "plateKindArabic": "plateKindArabic-16591862",
  "plateTypeCode": "plateTypeCode-16591862",
  "plateType": "plateType-16591862",
  "plateTypeArabic": "plateTypeArabic-16591862",
  "kindCode": "kindCode-16591862",
  "kind": "kind-16591862",
  "kindArabic": "kindArabic-16591862",
  "chasisNumber": "chasisNumber-16591862",
  "engineNumber": "engineNumber-16591862",
  "primaryVin": "primaryVin-16591862",
  "secondaryVin": "secondaryVin-16591862",
  "countryCode": "countryCode-16591862",
  "country": "country-16591862",
  "manfacturerCode": "manfacturerCode-16591862",
  "manfacturer": "manfacturer-16591862",
  "manfacturerArabic": "manfacturerArabic-16591862",
  "modelCode": "modelCode-16591862",
  "model": "model-16591862",
  "modelArabic": "modelArabic-16591862",
  "registrationYear": "registrationYear-16591862",
  "typeCode": "typeCode-16591862",
  "type": "type-16591862",
  "typeArabic": "typeArabic-16591862",
  "bodyColorCode": "bodyColorCode-16591862",
  "bodyColor": "bodyColor-16591862",
  "bodyColorArabic": "bodyColorArabic-16591862",
  "gearCode": "gearCode-16591862",
  "gearType": "gearType-16591862",
  "gearTypeArabic": "gearTypeArabic-16591862",
  "fuelCode": "fuelCode-16591862",
  "fuelType": "fuelType-16591862",
  "fuelTypeArabic": "fuelTypeArabic-16591862",
  "steeringCode": "steeringCode-16591862",
  "steeringSide": "steeringSide-16591862",
  "steeringSideArabic": "steeringSideArabic-16591862",
  "weightCode": "weightCode-16591862",
  "weightDisc": "weightDisc-16591862",
  "weightDiscArabic": "weightDiscArabic-16591862",
  "registrationDate": "2020-11-04T00:00:00.000Z",
  "registrationExpiryDate": "2004-06-10T00:00:00.000Z",
  "manufacturingYear": "manufacturingYear-16591862",
  "horsePower": "horsePower-16591862",
  "numberOfAxel": "numberOfAxel-16591862",
  "numberOfWheels": "numberOfWheels-16591862",
  "numberOfCylinders": "numberOfCylinders-16591862",
  "numberOfDoors": "numberOfDoors-16591862",
  "numberOfPassengers": "numberOfPassengers-16591862",
  "emptyWeight": "emptyWeight-16591862",
  "fullWeight": "fullWeight-16591862",
  "mileage": "mileage-16591862",
  "cubicCapacity": "cubicCapacity-16591862",
  "customer": "customer-16591862",
  "insuranceName": "insuranceName-16591862",
  "insuranceExpiry": "insuranceExpiry-16591862",
  "insuranceKind": "insuranceKind-16591862",
  "insuranceKindArabic": "insuranceKindArabic-16591862",
  "insurancePolicyNumber": "insurancePolicyNumber-16591862",
  "mortgageDescription": "mortgageDescription-16591862",
  "mortgageReference": "mortgageReference-16591862",
  "ownerTcfNumber": "ownerTcfNumber-16591862",
  "ownerTcfEnglishName": "ownerTcfEnglishName-16591862",
  "ownerTcfArabicName": "ownerTcfArabicName-16591862",
  "customCertificateNumber": "customCertificateNumber-16591862",
  "customCertificateDate": "2017-07-02T00:00:00.000Z",
  "customCertificateCenterCode": "customCertificateCenterCode-16591862",
  "customCertificateCenter": "customCertificateCenter-16591862",
  "registrationRemarks": "registrationRemarks-16591862",
  "nationalityCode": "nationalityCode-16591862",
  "nationality": "nationality-16591862",
  "nationalityArabic": "nationalityArabic-16591862",
  "createdAt": "2004-03-22T00:00:00.000Z",
  "createdBy": "createdBy.9vmd2@example.net",
  "modifiedAt": "2019-09-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.9vmd2@example.com"
}


### VehicleMasters
# @name VehicleMasters_DELETE
DELETE {{server}}/odata/v4/catalog/VehicleMasters/16591862-333e-47fc-a2aa-80e763f4769b
Content-Type: application/json
{{auth}}
